// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { validateEnvironment } from './envValidator';

// Validate environment variables on load
validateEnvironment();

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

console.log("client.ts: Initializing Supabase with URL:", SUPABASE_URL);
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error("client.ts: SUPABASE_PUBLISHABLE_KEY is missing!");
} else {
  console.log("client.ts: SUPABASE_PUBLISHABLE_KEY is present (starts with:", SUPABASE_PUBLISHABLE_KEY.substring(0, 5), ")");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});